### ISSUE TITLE
Please support Gnome on Xorg

### ISSUE THREAD

**Issue by Venemo** [mpiannucci/GnomeExtendedGestures#7]
Some of us are still stuck with Xorg for various reasons, but this extension only supports Gnome on Wayland. Could you please support X as well?

**Comment by mpiannucci** [comment]
Its not possible, the touchpad gestures do not work with libinput on x. only on wayland. I have no control over this, because I am using what is already parsed by the gnome-shell itself.

Sorry for the inconvenience.

**Comment by Venemo** [comment]
Thank you @mpiannucci for your answer. :) Have a nice day!
