### ISSUE TITLE
Test and Update for Gnome 3.24

### ISSUE THREAD

**Issue by mpiannucci** [mpiannucci/GnomeExtendedGestures#8]

**Comment by mpiannucci** [comment]
Updated event function calls for 3.24 but did not test because my linux partition is borked. 

Can someone let me know if this branch works on 3.24? https://github.com/mpiannucci/GnomeExtendedGestures/tree/shell_3.24

**Comment by gocarlos** [comment]
@mpiannucci I've tested it on Ubuntu Gnome 3.24, does not seem to do anything... The device is a thinkpad tp 260...

**Comment by mpiannucci** [comment]
Darn, that was the shell_3.24 branch right?

**Comment by gocarlos** [comment]
@mpiannucci sorry, I was not using wayland, it works now :)

**Comment by mpiannucci** [comment]
Awesome thank you!!!

Can you just confirm if you were using master or the shell_3.24 branch? So i know which one works for sure.

**Comment by gocarlos** [comment]
I'm using the shell_3.24, I've tested now the master branch also, but it does not work (did log out/in in between twice to make sure).

**Comment by mpiannucci** [comment]
Great thanks for all your help!
